name: Python Pro Otus Homework 01

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 src tests
    - name: Format black
      run: |
        poetry run black .
    - name: Format with black
      run: |
        poetry run black --check src tests
    - name: Sort imports with isort
      run: |
        poetry run isort --check-only src tests
    - name: Type check with mypy
      run: |
        poetry run mypy src tests
    - name: Test with pytest
      run: |
        poetry run pytest